// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace LogansFerry.TradingSuite.WebApp.Areas.StockData.Controllers
{
    public partial class UpdatePricesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UpdatePricesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult FlagAsExcluded()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.FlagAsExcluded);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UpdatePricesController Actions { get { return MVC.StockData.UpdatePrices; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "StockData";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "UpdatePrices";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "UpdatePrices";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string UpdateAllPrices = "UpdateAllPrices";
            public readonly string FlagAsExcluded = "FlagAsExcluded";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string UpdateAllPrices = "UpdateAllPrices";
            public const string FlagAsExcluded = "FlagAsExcluded";
        }


        static readonly ActionParamsClass_FlagAsExcluded s_params_FlagAsExcluded = new ActionParamsClass_FlagAsExcluded();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FlagAsExcluded FlagAsExcludedParams { get { return s_params_FlagAsExcluded; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FlagAsExcluded
        {
            public readonly string tickers = "tickers";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
            }
            public readonly string Index = "~/Areas/StockData/Views/UpdatePrices/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UpdatePricesController : LogansFerry.TradingSuite.WebApp.Areas.StockData.Controllers.UpdatePricesController
    {
        public T4MVC_UpdatePricesController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void UpdateAllPricesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult UpdateAllPrices()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateAllPrices);
            UpdateAllPricesOverride(callInfo);
            return callInfo;
        }

        partial void FlagAsExcludedOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, System.Collections.Generic.List<string> tickers);

        public override System.Web.Mvc.JsonResult FlagAsExcluded(System.Collections.Generic.List<string> tickers)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.FlagAsExcluded);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tickers", tickers);
            FlagAsExcludedOverride(callInfo, tickers);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
