// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace LogansFerry.TradingSuite.WebApp.Areas.StockData.Controllers
{
    public partial class ManageStocksController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ManageStocksController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult UpdateIsExcluded()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UpdateIsExcluded);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ManageStocksController Actions { get { return MVC.StockData.ManageStocks; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "StockData";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ManageStocks";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ManageStocks";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string UpdateStocks = "UpdateStocks";
            public readonly string UpdateIsExcluded = "UpdateIsExcluded";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string UpdateStocks = "UpdateStocks";
            public const string UpdateIsExcluded = "UpdateIsExcluded";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_UpdateIsExcluded s_params_UpdateIsExcluded = new ActionParamsClass_UpdateIsExcluded();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateIsExcluded UpdateIsExcludedParams { get { return s_params_UpdateIsExcluded; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateIsExcluded
        {
            public readonly string ticker = "ticker";
            public readonly string isExcluded = "isExcluded";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
            }
            public readonly string Index = "~/Areas/StockData/Views/ManageStocks/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ManageStocksController : LogansFerry.TradingSuite.WebApp.Areas.StockData.Controllers.ManageStocksController
    {
        public T4MVC_ManageStocksController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page);

        public override System.Web.Mvc.ActionResult Index(int? page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            IndexOverride(callInfo, page);
            return callInfo;
        }

        partial void UpdateStocksOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        public override System.Web.Mvc.JsonResult UpdateStocks()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UpdateStocks);
            UpdateStocksOverride(callInfo);
            return callInfo;
        }

        partial void UpdateIsExcludedOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string ticker, bool isExcluded);

        public override System.Web.Mvc.JsonResult UpdateIsExcluded(string ticker, bool isExcluded)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UpdateIsExcluded);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ticker", ticker);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isExcluded", isExcluded);
            UpdateIsExcludedOverride(callInfo, ticker, isExcluded);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
