//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("StockScreenerModel", "FK_CandlesticksToStocks_CandlesticksToStocks", "Candlesticks", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LogansFerry.BackTesterPrototype.Candlestick), "CandlesticksToStocks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogansFerry.BackTesterPrototype.CandlesticksToStock), true)]
[assembly: EdmRelationshipAttribute("StockScreenerModel", "FK_CandlesticksToStocks_Stocks", "Stocks", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LogansFerry.BackTesterPrototype.Stock), "CandlesticksToStocks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogansFerry.BackTesterPrototype.CandlesticksToStock), true)]
[assembly: EdmRelationshipAttribute("StockScreenerModel", "FK_Stocks_Exchanges", "Exchanges", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LogansFerry.BackTesterPrototype.Exchanx), "Stocks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogansFerry.BackTesterPrototype.Stock), true)]
[assembly: EdmRelationshipAttribute("StockScreenerModel", "FK_StockDailies_Stocks", "Stocks", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LogansFerry.BackTesterPrototype.Stock), "StockDailies", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogansFerry.BackTesterPrototype.StockDaily), true)]
[assembly: EdmRelationshipAttribute("StockScreenerModel", "WatchListsToStocks", "Stocks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogansFerry.BackTesterPrototype.Stock), "Watchlists", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogansFerry.BackTesterPrototype.Watchlist))]

#endregion

namespace LogansFerry.BackTesterPrototype
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StockScreenerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StockScreenerEntities object using the connection string found in the 'StockScreenerEntities' section of the application configuration file.
        /// </summary>
        public StockScreenerEntities() : base("name=StockScreenerEntities", "StockScreenerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StockScreenerEntities object.
        /// </summary>
        public StockScreenerEntities(string connectionString) : base(connectionString, "StockScreenerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StockScreenerEntities object.
        /// </summary>
        public StockScreenerEntities(EntityConnection connection) : base(connection, "StockScreenerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Candlestick> Candlesticks
        {
            get
            {
                if ((_Candlesticks == null))
                {
                    _Candlesticks = base.CreateObjectSet<Candlestick>("Candlesticks");
                }
                return _Candlesticks;
            }
        }
        private ObjectSet<Candlestick> _Candlesticks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CandlesticksToStock> CandlesticksToStocks
        {
            get
            {
                if ((_CandlesticksToStocks == null))
                {
                    _CandlesticksToStocks = base.CreateObjectSet<CandlesticksToStock>("CandlesticksToStocks");
                }
                return _CandlesticksToStocks;
            }
        }
        private ObjectSet<CandlesticksToStock> _CandlesticksToStocks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Exchanx> Exchanges
        {
            get
            {
                if ((_Exchanges == null))
                {
                    _Exchanges = base.CreateObjectSet<Exchanx>("Exchanges");
                }
                return _Exchanges;
            }
        }
        private ObjectSet<Exchanx> _Exchanges;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StockDaily> StockDailies
        {
            get
            {
                if ((_StockDailies == null))
                {
                    _StockDailies = base.CreateObjectSet<StockDaily>("StockDailies");
                }
                return _StockDailies;
            }
        }
        private ObjectSet<StockDaily> _StockDailies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Stock> Stocks
        {
            get
            {
                if ((_Stocks == null))
                {
                    _Stocks = base.CreateObjectSet<Stock>("Stocks");
                }
                return _Stocks;
            }
        }
        private ObjectSet<Stock> _Stocks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Watchlist> Watchlists
        {
            get
            {
                if ((_Watchlists == null))
                {
                    _Watchlists = base.CreateObjectSet<Watchlist>("Watchlists");
                }
                return _Watchlists;
            }
        }
        private ObjectSet<Watchlist> _Watchlists;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Candlesticks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCandlesticks(Candlestick candlestick)
        {
            base.AddObject("Candlesticks", candlestick);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CandlesticksToStocks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCandlesticksToStocks(CandlesticksToStock candlesticksToStock)
        {
            base.AddObject("CandlesticksToStocks", candlesticksToStock);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Exchanges EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExchanges(Exchanx exchanx)
        {
            base.AddObject("Exchanges", exchanx);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StockDailies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStockDailies(StockDaily stockDaily)
        {
            base.AddObject("StockDailies", stockDaily);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Stocks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStocks(Stock stock)
        {
            base.AddObject("Stocks", stock);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Watchlists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWatchlists(Watchlist watchlist)
        {
            base.AddObject("Watchlists", watchlist);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StockScreenerModel", Name="Candlestick")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Candlestick : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Candlestick object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="numOccurrences">Initial value of the NumOccurrences property.</param>
        /// <param name="lumenRating">Initial value of the LumenRating property.</param>
        public static Candlestick CreateCandlestick(global::System.Int32 id, global::System.String name, global::System.Int32 numOccurrences, global::System.Int32 lumenRating)
        {
            Candlestick candlestick = new Candlestick();
            candlestick.ID = id;
            candlestick.Name = name;
            candlestick.NumOccurrences = numOccurrences;
            candlestick.LumenRating = lumenRating;
            return candlestick;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumOccurrences
        {
            get
            {
                return _NumOccurrences;
            }
            set
            {
                OnNumOccurrencesChanging(value);
                ReportPropertyChanging("NumOccurrences");
                _NumOccurrences = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumOccurrences");
                OnNumOccurrencesChanged();
            }
        }
        private global::System.Int32 _NumOccurrences;
        partial void OnNumOccurrencesChanging(global::System.Int32 value);
        partial void OnNumOccurrencesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LumenRating
        {
            get
            {
                return _LumenRating;
            }
            set
            {
                OnLumenRatingChanging(value);
                ReportPropertyChanging("LumenRating");
                _LumenRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LumenRating");
                OnLumenRatingChanged();
            }
        }
        private global::System.Int32 _LumenRating;
        partial void OnLumenRatingChanging(global::System.Int32 value);
        partial void OnLumenRatingChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockScreenerModel", "FK_CandlesticksToStocks_CandlesticksToStocks", "CandlesticksToStocks")]
        public EntityCollection<CandlesticksToStock> CandlesticksToStocks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CandlesticksToStock>("StockScreenerModel.FK_CandlesticksToStocks_CandlesticksToStocks", "CandlesticksToStocks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CandlesticksToStock>("StockScreenerModel.FK_CandlesticksToStocks_CandlesticksToStocks", "CandlesticksToStocks", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StockScreenerModel", Name="CandlesticksToStock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CandlesticksToStock : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CandlesticksToStock object.
        /// </summary>
        /// <param name="candlestickId">Initial value of the CandlestickId property.</param>
        /// <param name="exchange">Initial value of the Exchange property.</param>
        /// <param name="ticker">Initial value of the Ticker property.</param>
        /// <param name="numOccurrences">Initial value of the NumOccurrences property.</param>
        /// <param name="lumenRating">Initial value of the LumenRating property.</param>
        public static CandlesticksToStock CreateCandlesticksToStock(global::System.Int32 candlestickId, global::System.String exchange, global::System.String ticker, global::System.Int32 numOccurrences, global::System.Int32 lumenRating)
        {
            CandlesticksToStock candlesticksToStock = new CandlesticksToStock();
            candlesticksToStock.CandlestickId = candlestickId;
            candlesticksToStock.Exchange = exchange;
            candlesticksToStock.Ticker = ticker;
            candlesticksToStock.NumOccurrences = numOccurrences;
            candlesticksToStock.LumenRating = lumenRating;
            return candlesticksToStock;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CandlestickId
        {
            get
            {
                return _CandlestickId;
            }
            set
            {
                if (_CandlestickId != value)
                {
                    OnCandlestickIdChanging(value);
                    ReportPropertyChanging("CandlestickId");
                    _CandlestickId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CandlestickId");
                    OnCandlestickIdChanged();
                }
            }
        }
        private global::System.Int32 _CandlestickId;
        partial void OnCandlestickIdChanging(global::System.Int32 value);
        partial void OnCandlestickIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Exchange
        {
            get
            {
                return _Exchange;
            }
            set
            {
                if (_Exchange != value)
                {
                    OnExchangeChanging(value);
                    ReportPropertyChanging("Exchange");
                    _Exchange = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Exchange");
                    OnExchangeChanged();
                }
            }
        }
        private global::System.String _Exchange;
        partial void OnExchangeChanging(global::System.String value);
        partial void OnExchangeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ticker
        {
            get
            {
                return _Ticker;
            }
            set
            {
                if (_Ticker != value)
                {
                    OnTickerChanging(value);
                    ReportPropertyChanging("Ticker");
                    _Ticker = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Ticker");
                    OnTickerChanged();
                }
            }
        }
        private global::System.String _Ticker;
        partial void OnTickerChanging(global::System.String value);
        partial void OnTickerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumOccurrences
        {
            get
            {
                return _NumOccurrences;
            }
            set
            {
                OnNumOccurrencesChanging(value);
                ReportPropertyChanging("NumOccurrences");
                _NumOccurrences = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumOccurrences");
                OnNumOccurrencesChanged();
            }
        }
        private global::System.Int32 _NumOccurrences;
        partial void OnNumOccurrencesChanging(global::System.Int32 value);
        partial void OnNumOccurrencesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LumenRating
        {
            get
            {
                return _LumenRating;
            }
            set
            {
                OnLumenRatingChanging(value);
                ReportPropertyChanging("LumenRating");
                _LumenRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LumenRating");
                OnLumenRatingChanged();
            }
        }
        private global::System.Int32 _LumenRating;
        partial void OnLumenRatingChanging(global::System.Int32 value);
        partial void OnLumenRatingChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockScreenerModel", "FK_CandlesticksToStocks_CandlesticksToStocks", "Candlesticks")]
        public Candlestick Candlestick
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candlestick>("StockScreenerModel.FK_CandlesticksToStocks_CandlesticksToStocks", "Candlesticks").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candlestick>("StockScreenerModel.FK_CandlesticksToStocks_CandlesticksToStocks", "Candlesticks").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Candlestick> CandlestickReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candlestick>("StockScreenerModel.FK_CandlesticksToStocks_CandlesticksToStocks", "Candlesticks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Candlestick>("StockScreenerModel.FK_CandlesticksToStocks_CandlesticksToStocks", "Candlesticks", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockScreenerModel", "FK_CandlesticksToStocks_Stocks", "Stocks")]
        public Stock Stock
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stock>("StockScreenerModel.FK_CandlesticksToStocks_Stocks", "Stocks").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stock>("StockScreenerModel.FK_CandlesticksToStocks_Stocks", "Stocks").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Stock> StockReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stock>("StockScreenerModel.FK_CandlesticksToStocks_Stocks", "Stocks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Stock>("StockScreenerModel.FK_CandlesticksToStocks_Stocks", "Stocks", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StockScreenerModel", Name="Exchanx")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Exchanx : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Exchanx object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Exchanx CreateExchanx(global::System.String id, global::System.String name)
        {
            Exchanx exchanx = new Exchanx();
            exchanx.ID = id;
            exchanx.Name = name;
            return exchanx;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockScreenerModel", "FK_Stocks_Exchanges", "Stocks")]
        public EntityCollection<Stock> Stocks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Stock>("StockScreenerModel.FK_Stocks_Exchanges", "Stocks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Stock>("StockScreenerModel.FK_Stocks_Exchanges", "Stocks", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StockScreenerModel", Name="Stock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Stock : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Stock object.
        /// </summary>
        /// <param name="exchange">Initial value of the Exchange property.</param>
        /// <param name="ticker">Initial value of the Ticker property.</param>
        /// <param name="companyName">Initial value of the CompanyName property.</param>
        public static Stock CreateStock(global::System.String exchange, global::System.String ticker, global::System.String companyName)
        {
            Stock stock = new Stock();
            stock.Exchange = exchange;
            stock.Ticker = ticker;
            stock.CompanyName = companyName;
            return stock;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Exchange
        {
            get
            {
                return _Exchange;
            }
            set
            {
                if (_Exchange != value)
                {
                    OnExchangeChanging(value);
                    ReportPropertyChanging("Exchange");
                    _Exchange = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Exchange");
                    OnExchangeChanged();
                }
            }
        }
        private global::System.String _Exchange;
        partial void OnExchangeChanging(global::System.String value);
        partial void OnExchangeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ticker
        {
            get
            {
                return _Ticker;
            }
            set
            {
                if (_Ticker != value)
                {
                    OnTickerChanging(value);
                    ReportPropertyChanging("Ticker");
                    _Ticker = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Ticker");
                    OnTickerChanged();
                }
            }
        }
        private global::System.String _Ticker;
        partial void OnTickerChanging(global::System.String value);
        partial void OnTickerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                OnCompanyNameChanging(value);
                ReportPropertyChanging("CompanyName");
                _CompanyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CompanyName");
                OnCompanyNameChanged();
            }
        }
        private global::System.String _CompanyName;
        partial void OnCompanyNameChanging(global::System.String value);
        partial void OnCompanyNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockScreenerModel", "FK_CandlesticksToStocks_Stocks", "CandlesticksToStocks")]
        public EntityCollection<CandlesticksToStock> CandlesticksToStocks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CandlesticksToStock>("StockScreenerModel.FK_CandlesticksToStocks_Stocks", "CandlesticksToStocks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CandlesticksToStock>("StockScreenerModel.FK_CandlesticksToStocks_Stocks", "CandlesticksToStocks", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockScreenerModel", "FK_Stocks_Exchanges", "Exchanges")]
        public Exchanx Exchanx
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Exchanx>("StockScreenerModel.FK_Stocks_Exchanges", "Exchanges").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Exchanx>("StockScreenerModel.FK_Stocks_Exchanges", "Exchanges").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Exchanx> ExchanxReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Exchanx>("StockScreenerModel.FK_Stocks_Exchanges", "Exchanges");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Exchanx>("StockScreenerModel.FK_Stocks_Exchanges", "Exchanges", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockScreenerModel", "FK_StockDailies_Stocks", "StockDailies")]
        public EntityCollection<StockDaily> StockDailies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StockDaily>("StockScreenerModel.FK_StockDailies_Stocks", "StockDailies");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StockDaily>("StockScreenerModel.FK_StockDailies_Stocks", "StockDailies", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockScreenerModel", "WatchListsToStocks", "Watchlists")]
        public EntityCollection<Watchlist> Watchlists
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Watchlist>("StockScreenerModel.WatchListsToStocks", "Watchlists");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Watchlist>("StockScreenerModel.WatchListsToStocks", "Watchlists", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StockScreenerModel", Name="StockDaily")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StockDaily : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StockDaily object.
        /// </summary>
        /// <param name="exchange">Initial value of the Exchange property.</param>
        /// <param name="ticker">Initial value of the Ticker property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="openPrice">Initial value of the OpenPrice property.</param>
        /// <param name="closePrice">Initial value of the ClosePrice property.</param>
        /// <param name="highPrice">Initial value of the HighPrice property.</param>
        /// <param name="lowPrice">Initial value of the LowPrice property.</param>
        /// <param name="volume">Initial value of the Volume property.</param>
        public static StockDaily CreateStockDaily(global::System.String exchange, global::System.String ticker, global::System.DateTime date, global::System.Single openPrice, global::System.Single closePrice, global::System.Single highPrice, global::System.Single lowPrice, global::System.Int32 volume)
        {
            StockDaily stockDaily = new StockDaily();
            stockDaily.Exchange = exchange;
            stockDaily.Ticker = ticker;
            stockDaily.Date = date;
            stockDaily.OpenPrice = openPrice;
            stockDaily.ClosePrice = closePrice;
            stockDaily.HighPrice = highPrice;
            stockDaily.LowPrice = lowPrice;
            stockDaily.Volume = volume;
            return stockDaily;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Exchange
        {
            get
            {
                return _Exchange;
            }
            set
            {
                if (_Exchange != value)
                {
                    OnExchangeChanging(value);
                    ReportPropertyChanging("Exchange");
                    _Exchange = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Exchange");
                    OnExchangeChanged();
                }
            }
        }
        private global::System.String _Exchange;
        partial void OnExchangeChanging(global::System.String value);
        partial void OnExchangeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ticker
        {
            get
            {
                return _Ticker;
            }
            set
            {
                if (_Ticker != value)
                {
                    OnTickerChanging(value);
                    ReportPropertyChanging("Ticker");
                    _Ticker = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Ticker");
                    OnTickerChanged();
                }
            }
        }
        private global::System.String _Ticker;
        partial void OnTickerChanging(global::System.String value);
        partial void OnTickerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                if (_Date != value)
                {
                    OnDateChanging(value);
                    ReportPropertyChanging("Date");
                    _Date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date");
                    OnDateChanged();
                }
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single OpenPrice
        {
            get
            {
                return _OpenPrice;
            }
            set
            {
                OnOpenPriceChanging(value);
                ReportPropertyChanging("OpenPrice");
                _OpenPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OpenPrice");
                OnOpenPriceChanged();
            }
        }
        private global::System.Single _OpenPrice;
        partial void OnOpenPriceChanging(global::System.Single value);
        partial void OnOpenPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single ClosePrice
        {
            get
            {
                return _ClosePrice;
            }
            set
            {
                OnClosePriceChanging(value);
                ReportPropertyChanging("ClosePrice");
                _ClosePrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClosePrice");
                OnClosePriceChanged();
            }
        }
        private global::System.Single _ClosePrice;
        partial void OnClosePriceChanging(global::System.Single value);
        partial void OnClosePriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single HighPrice
        {
            get
            {
                return _HighPrice;
            }
            set
            {
                OnHighPriceChanging(value);
                ReportPropertyChanging("HighPrice");
                _HighPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HighPrice");
                OnHighPriceChanged();
            }
        }
        private global::System.Single _HighPrice;
        partial void OnHighPriceChanging(global::System.Single value);
        partial void OnHighPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single LowPrice
        {
            get
            {
                return _LowPrice;
            }
            set
            {
                OnLowPriceChanging(value);
                ReportPropertyChanging("LowPrice");
                _LowPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LowPrice");
                OnLowPriceChanged();
            }
        }
        private global::System.Single _LowPrice;
        partial void OnLowPriceChanging(global::System.Single value);
        partial void OnLowPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                OnVolumeChanging(value);
                ReportPropertyChanging("Volume");
                _Volume = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Volume");
                OnVolumeChanged();
            }
        }
        private global::System.Int32 _Volume;
        partial void OnVolumeChanging(global::System.Int32 value);
        partial void OnVolumeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockScreenerModel", "FK_StockDailies_Stocks", "Stocks")]
        public Stock Stock
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stock>("StockScreenerModel.FK_StockDailies_Stocks", "Stocks").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stock>("StockScreenerModel.FK_StockDailies_Stocks", "Stocks").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Stock> StockReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stock>("StockScreenerModel.FK_StockDailies_Stocks", "Stocks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Stock>("StockScreenerModel.FK_StockDailies_Stocks", "Stocks", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StockScreenerModel", Name="Watchlist")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Watchlist : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Watchlist object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Watchlist CreateWatchlist(global::System.Int32 id, global::System.String name)
        {
            Watchlist watchlist = new Watchlist();
            watchlist.ID = id;
            watchlist.Name = name;
            return watchlist;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockScreenerModel", "WatchListsToStocks", "Stocks")]
        public EntityCollection<Stock> Stocks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Stock>("StockScreenerModel.WatchListsToStocks", "Stocks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Stock>("StockScreenerModel.WatchListsToStocks", "Stocks", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
